### ISSUE TITLE
page deploy is failing with 5XX

### ISSUE THREAD

**Issue by learn2project** [actions/deploy-pages#193]
We are trying to deploy to github pages via github action and it is failing with 5XX error.  Using GitHub enterprise server 3.8.3.

```
  - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
          
      - name: read deploy path
        run: |
          echo "${{steps.deployment.outputs.page_url}}"
          
         
```

Error we are getting: 

```
Error: Request failed with status code 500
    at createError (/runner/_work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/runner/_work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/runner/_work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/adapters/http.js:293:1)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:13[45](https://org:repo/13:46):12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


Error: Failed to create deployment (status: 500) with build version 534b03edbb340cd7891ab55799cded941a935f21. Server error, is githubstatus.com reporting a Pages outage? Please re-run the deployment at a later time.
```
It is most likely catching this : https://github.com/actions/deploy-pages/blob/main/src/internal/deployment.js#L125

Any pointer where it may be wrong ?

**Comment by yoannchaudet** [comment]
Hello, thanks for reaching out.

Hard to tell what the issue could be without a support bundle. Would you mind opening a support ticket [here](https://support.github.com/contact)? We will want to look at service logs to understand the issue.

**Comment by JamesMGreene** [comment]
Please feel free to reopen with more information (or submit a support bundle) if you're still running into this issue. Thanks!
