### ISSUE TITLE
Invalid artifact URL with v1.2.9

### ISSUE THREAD

**Issue by jcop** [actions/deploy-pages#235]
Hi there

I saw that the [invalid artifact url](https://github.com/actions/deploy-pages/issues/225#) fix was [backported into v1](https://github.com/actions/deploy-pages/releases), however I'm still getting the Invalid artifact url message.

I'm using Github  Enterprise Server 3.8.6

Could this be an error on my side, or some particular quirk with the 3.8 version?

Thanks in advance!

```
Run actions/deploy-pages@v1.2.9
  with:
    emit_telemetry: false
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: 5000
    artifact_name: github-pages
    preview: false
Artifact exchange URL: https://***.com/_services/pipelines/z0Rk2ueWXp3kDK4JaspYI3r0zHdPc48yPbeq5Lx4ZyeInmcFuS/_apis/pipelines/workflows/2827897/artifacts?api-version=6.0-preview


Creating Pages deployment with payload:
{
	"artifact_url": "https://**.com/_services/pipelines/z0Rk2ueWXp3kDK4JaspYI3r0zHdPc48yPbeq5Lx4ZyeInmcFuS/_apis/pipelines/1/runs/22/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "6e942b73c5261ea98bb46cd25574c13a306cb367",
	"oidc_token": "***"
}


Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url
    at /runner/_work/_actions/actions/deploy-pages/v1.2.9/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/runner/_work/_actions/actions/deploy-pages/v1.2.9/webpack:/deploy-pages/src/api-client.js:116:1)
    at Deployment.create (/runner/_work/_actions/actions/deploy-pages/v1.2.9/webpack:/deploy-pages/src/deployment.js:59:1)
    at main (/runner/_work/_actions/actions/deploy-pages/v1.2.9/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version 6e942b73c5261ea98bb46cd25574c13a306cb367. Responded with: Invalid artifact url
```

**Comment by Anubiso** [comment]
We have the same issue. We are using 1.2.9 too, with actions/upload-pages-artifact@v2 running successfully before.

**Comment by Anubiso** [comment]
Any updates on this? We are still encountering the same issue on GitHub Enterprise Server 3.8.8 with deploy-pages 1.2.9

**Comment by JamesMGreene** [comment]
Regarding the issue mentioned:
- https://github.com/actions/deploy-pages/issues/225

That was not fixed by any changes to this action. That was a temporary incident caused by an unexpected mismatch between a GitHub Actions subdomain format change being rolled out and the security checks that GitHub Pages was doing to verify the referenced artifact on the server side. That incident would not have affected GHES usage.

For this one, you may want to file an issue with Support. 🤔

It's possible that Actions may have backported a similar change without the equivalent Pages fix, though it feels unlikely to me. I'm not too familiar with the Actions/artifacts system configuration on GHES, unfortunately. 😕

**Comment by JamesMGreene** [comment]
@jcop @Anubiso Actually, question for each of you:

Does your artifact exchange URL's hostname (masked as `***.com` in the OP) **exactly** **match** your GHES appliance's hostname? e.g. both are exactly `github.mycompany.com` or whatever

Curious if this an untested case with [GHES subdomain isolation](https://docs.github.com/en/enterprise-server@3.8/admin/configuration/hardening-security-for-your-enterprise/enabling-subdomain-isolation) enabled or something like that. 🤔
