### ISSUE TITLE
Deploy request keep fails with 400 error.

### ISSUE THREAD

**Issue by Clarit7** [actions/deploy-pages#25]
About few hours ago, I tried to change my pages.
After several pull requests, the deploying process suddenly failed and it keeps failing so far.

```
Actor: github-pages[bot]
Action ID: 2053521171
Artifact URL: https://pipelines.actions.githubusercontent.com/fg4udqL2Wa82qoAxzxN3RnaFg6dw3vrWz4bACOBlaxNtoOR89J/_apis/pipelines/workflows/2053521171/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":9456527,"size":23541760,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/fg4udqL2Wa82qoAxzxN3RnaFg6dw3vrWz4bACOBlaxNtoOR89J/_apis/resources/Containers/9456527","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/fg4udqL2Wa82qoAxzxN3RnaFg6dw3vrWz4bACOBlaxNtoOR89J/_apis/pipelines/1/runs/101/artifacts?artifactName=github-pages","expiresOn":"2022-06-26T16:16:23.5374012Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/fg4udqL2Wa82qoAxzxN3RnaFg6dw3vrWz4bACOBlaxNtoOR89J/_apis/pipelines/1/runs/101/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "e95f420697a9e5931990b6cc697fe85bf5c5c6f4",
	"oidc_token": "***"
}
Failed to create deployment for e95f420697a9e5931990b6cc697fe85bf5c5c6f4.
{"message":"Deployment request failed for e95f420697a9e5931990b6cc697fe85bf5c5c6f4 due to in progress deployment. Please cancel 51542b8f73858241b61d5a1951652e55f5c041e9 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 400
Error: Error: Request failed with status code 400
Sending telemetry for run id 2053521171
```

I couldn't find workflow '51542b8f73858241b61d5a1951652e55f5c041e9'.
Also workflow which status is 'queued' or 'in progress' doesn't exist so that I cannot stop anything.
Furthermore, sometimes server returns 502 error too.

What should I do?

edited : Is this problem same with last issue? [https://github.com/actions/deploy-pages/issues/22](https://github.com/actions/deploy-pages/issues/22)
It seems people currently talking about same problem.

**Comment by artegoser** [comment]
If you restart workflow, then there is an endless updating of pages

**Comment by KevinKoetz** [comment]
Same error on my end now. 
However i had a in-Progress deployment before getting the 400. This deployment was stuck on Current_status: updating Pages.
When pushing again to the gh-pages branch it seems that the cancelation failed:

```
Deployment cancellation failed Error: Request failed with status code 401
    at createError (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/axios/lib/adapters/http.js:293:1)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      Authorization: '***',
      'User-Agent': 'axios/0.24.0',
      'Content-Length': 2
    },
    method: 'put',
    url: 'https://api.github.com/repos/KevinKoetz/todo/pages/deployment/cancel/a51af721c6c52aff6e615cf437faf4ea9aabd830',
    data: '{}'
  }
```

**Comment by LeotomasMC** [comment]
looks like github is having issues again https://www.githubstatus.com/incidents/z95g34pl8rdm
