### ISSUE TITLE
HttpError: Invalid environment node id

### ISSUE THREAD

**Issue by stuchalk** [actions/deploy-pages#271]
Running either v2 or v3 of pages-deploy I am running into the following error that causes my action to fail.

```
Run actions/deploy-pages@v3
  with:
    token: ***
    timeout: 600000
    error_count: 10
    reporting_interval: 5000
    artifact_name: github-pages
    preview: false
  env:
    BASE_URL: /WFChemCookbook
    pythonLocation: /opt/hostedtoolcache/Python/3.11.6/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.6/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.6/x64/lib
Artifact exchange URL: https://pipelinesghubeus7.actions.githubusercontent.com/LUhykx9u3CmfjRFCi2VwEWvofWZTH9U1ktJ1VebNrL0iIdRboZ/_apis/pipelines/workflows/7118278931/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus7.actions.githubusercontent.com/LUhykx9u3CmfjRFCi2VwEWvofWZTH9U1ktJ1VebNrL0iIdRboZ/_apis/pipelines/1/runs/26/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "ca001e42a30fd6d1cbc21442d8dbe63a0a5ed344",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Invalid environment node id
    at /home/runner/work/_actions/actions/deploy-pages/v3/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v3/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v3/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v3/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 500) with build version ca001e42a30fd6d1cbc21442d8dbe63a0a5ed344. Server error, is githubstatus.com reporting a Pages outage? Please re-run the deployment at a later time.
```

This looks like a GitHub server issue but looking at githubstatus.com actions and page are not reporting any issues.

Any ideas how to address this error?

**Comment by Dailoge** [comment]
good answer, for example

# ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

**Comment by lalen-unicity** [comment]
thanks!

**Comment by lalen-unicity** [comment]
> I just had the same issue,
> 
> I could fix it by adding
> 
> > ```
> > environment:
> >   name: github-pages
> > ```
> 
> Also need to switch to build and deploy by "github Action" in https://github.com/YOUR_REPOSITORY/settings/pages

thanks you !
