### ISSUE TITLE
 Error: No artifacts named "github-pages" were found for this workflow run.

### ISSUE THREAD

**Issue by dskvr** [actions/deploy-pages#305]
- Was ran with debug logging on
- Tried many solutions before coming here
- permissions appear to be correctly set

## From `actions/update-pages-artifact` step
```
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Evaluating: inputs.name
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'name'
##[debug]=> 'github-pages'
##[debug]Result: 'github-pages'
...
##[debug]Artifact github-pages has been successfully uploaded, total size in bytes: 133120
```

## From "Artifacts" section in summary
![Screenshot_20240128_221843](https://github.com/actions/deploy-pages/assets/299465/38c63b6b-6996-499c-b168-9acb36588739)

## From `actions/deploy-pages`
```
##[debug]Headers: {
##[debug]  "content-length": "16",
##[debug]  "content-type": "application/json",
##[debug]  "date": "*** GMT",
##[debug]  "x-github-backend": "Kubernetes",
##[debug]  "x-github-request-id": "***"
##[debug]}
##[debug]Body: {
##[debug]  "artifacts": []
##[debug]}
Found 0 artifact(s)
##[debug]List artifact count: 0
Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages, or Actions? Please re-run the deployment at a later time.
Error: Error: No artifacts named "github-pages" were found for this workflow run. Ensure artifacts are uploaded with actions/artifact@v4 or later.
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:85:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: No artifacts named "github-pages" were found for this workflow run. Ensure artifacts are uploaded with actions/artifact@v4 or later.
##[debug]Node Action run completed with exit code 1
```

:question:

**Comment by yoannchaudet** [comment]
👋 

You are using our latest `deploy-pages` Actions (v4) which leverage the new Actions Artifact feature. Just try to also update `upload-pages-artifact` to the latest (which is v3).

**Comment by caco3** [comment]
I have the very same issue. v3 still works, v4 throws this error.

**Comment by kuboon** [comment]
Adding config before deploy worked for me

```yaml
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Configure Pages
      uses: actions/configure-pages@v4
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
```

**Comment by caco3** [comment]
Hmm, not sure if this is the solution, because that's what we had more or less (Just additionally `actions/upload-pages-artifact@v2` between):
See https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/.github/workflows/build.yaml#L421

**Comment by ZhQuella** [comment]
```yml
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.6.2

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: List build directory
        run: ls -R ${{ github.workspace }}/sample/dist

      - name: Set debug output
        run: echo "UPLOAD_PATH=${{ github.workspace }}/sample/dist" >> $GITHUB_ENV

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/dist
          artifact_name: dist
        continue-on-error: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
