### ISSUE TITLE
HttpError: Validation Failed when deploying using deploy-pages@v4

### ISSUE THREAD

**Issue by franccesco** [actions/deploy-pages#380]
Hello, I recently pushed changes to the main branch to a private repo with no changes to the workflow that deploys to Github Pages. I tried bumping the version of deploy-pages from v4 to v4.0.5 with no luck. Could you help me point out if this is something on my end?

Here's my workflow:
```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Generate YARD documentation
        run: |
          bundle exec yard doc
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'doc'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
```

And the deployment logs that's giving me the error. I'm happy to share the full logs including other steps if needed:
```
##[debug]Evaluating condition for step: 'Deploy to GitHub Pages'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy to GitHub Pages
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run actions/deploy-pages@v4.0.5
##[debug]all variables are set
##[debug]all variables are set
##[debug]ID token url is https://pipelinesghubeus26.actions.githubusercontent.com/BgUOrW478Ds3HT8ENoabg8fCJhkzqkbC2eaIINbgrlClQFFTrR/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/a74b1e49-7d36-49f0-8b69-a12783756156/jobs/e07742bd-189a-5079-918b-43f8b2f94b89/idtoken?api-version=2.0
::add-mask::***
##[debug]Actor: franccesco
##[debug]Action ID: deployment
##[debug]Actions Workflow Run ID: 11623588806
Fetching artifact metadata for "github-pages" in this workflow run
##[debug]Workflow Run Backend ID: a74b1e49-7d36-49f0-8b69-a12783756156
##[debug]Workflow Job Run Backend ID: e07742bd-189a-5079-918b-43f8b2f94b89
##[debug][Request] ListArtifacts https://results-receiver.actions.githubusercontent.com/twirp/github.actions.results.api.v1.ArtifactService/ListArtifacts
##[debug][Response] - 200
##[debug]Headers: {
##[debug]  "content-length": "251",
##[debug]  "content-type": "application/json",
##[debug]  "date": "Fri, 01 Nov 2024 12:05:32 GMT",
##[debug]  "x-github-backend": "Kubernetes",
##[debug]  "x-github-request-id": "A8C3:2DA894:E15EB8:13FEE2F:6724C40C"
##[debug]}
##[debug]Body: {
##[debug]  "artifacts": [
##[debug]    {
##[debug]      "workflow_run_backend_id": "a74b1e49-7d36-49f0-8b69-a12783756156",
##[debug]      "workflow_job_run_backend_id": "e07742bd-189a-5079-918b-43f8b2f94b89",
##[debug]      "database_id": "2132837049",
##[debug]      "name": "github-pages",
##[debug]      "size": "74368",
##[debug]      "created_at": "2024-11-01T12:05:31Z"
##[debug]    }
##[debug]  ]
##[debug]}
Found 1 artifact(s)
##[debug]List artifact count: 1
##[debug]Artifact: {"name":"github-pages","id":2132837049,"size":74368,"createdAt":"2024-11-01T12:05:31.000Z"}
Creating Pages deployment with payload:
{
	"artifact_id": 2132837049,
	"pages_build_version": "d8fac135839fd4d5cf0d1dae104004c1deacff3d",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Validation Failed
    at /home/runner/work/_actions/actions/deploy-pages/v4.0.5/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4.0.5/src/internal/api-client.js:125:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4.0.5/src/internal/deployment.js:74:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4.0.5/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 422) with build version d8fac135839fd4d5cf0d1dae104004c1deacff3d. Request ID A8C1:7C509:AE023B3:1518DED1:6724C40C
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy to GitHub Pages
```

Thank you in advance.

**Comment by franccesco** [comment]
This is on my end, and I solved it. It seems my account was downgraded from Pro to Free, which made the GitHub Pages deployment on a private repo fail.
